"""Initial migration

Revision ID: 84e86493f0d8
Revises:
Create Date: 2025-11-05 20:20:31.410062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84e86493f0d8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mash",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("grain_temp", sa.Integer(), nullable=True),
        sa.Column("tun_temp", sa.Integer(), nullable=True),
        sa.Column("sparge_temp", sa.Integer(), nullable=True),
        sa.Column("ph", sa.Integer(), nullable=True),
        sa.Column("tun_weight", sa.Integer(), nullable=True),
        sa.Column("tun_specific_heat", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("display_grain_temp", sa.String(length=255), nullable=True),
        sa.Column("display_tun_temp", sa.String(length=255), nullable=True),
        sa.Column("display_sparge_temp", sa.String(length=255), nullable=True),
        sa.Column("display_tun_weight", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mash_id"), "mash", ["id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.create_index(
        op.f("ix_questions_question_text"), "questions", ["question_text"], unique=False
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_batch", sa.Boolean(), nullable=True),
        sa.Column("origin_recipe_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("brewer", sa.String(), nullable=True),
        sa.Column("asst_brewer", sa.String(), nullable=True),
        sa.Column("batch_size", sa.Float(), nullable=True),
        sa.Column("boil_size", sa.Float(), nullable=True),
        sa.Column("boil_time", sa.Integer(), nullable=True),
        sa.Column("efficiency", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("taste_notes", sa.String(), nullable=True),
        sa.Column("taste_rating", sa.Integer(), nullable=True),
        sa.Column("og", sa.Float(), nullable=True),
        sa.Column("fg", sa.Float(), nullable=True),
        sa.Column("fermentation_stages", sa.Integer(), nullable=True),
        sa.Column("primary_age", sa.Integer(), nullable=True),
        sa.Column("primary_temp", sa.Float(), nullable=True),
        sa.Column("secondary_age", sa.Integer(), nullable=True),
        sa.Column("secondary_temp", sa.Float(), nullable=True),
        sa.Column("tertiary_age", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("age_temp", sa.Float(), nullable=True),
        sa.Column("carbonation_used", sa.String(), nullable=True),
        sa.Column("est_og", sa.Float(), nullable=True),
        sa.Column("est_fg", sa.Float(), nullable=True),
        sa.Column("est_color", sa.Float(), nullable=True),
        sa.Column("ibu", sa.Float(), nullable=True),
        sa.Column("ibu_method", sa.String(), nullable=True),
        sa.Column("est_abv", sa.Float(), nullable=True),
        sa.Column("abv", sa.Float(), nullable=True),
        sa.Column("actual_efficiency", sa.Float(), nullable=True),
        sa.Column("calories", sa.Float(), nullable=True),
        sa.Column("display_batch_size", sa.String(), nullable=True),
        sa.Column("display_boil_size", sa.String(), nullable=True),
        sa.Column("display_og", sa.String(), nullable=True),
        sa.Column("display_fg", sa.String(), nullable=True),
        sa.Column("display_primary_temp", sa.String(), nullable=True),
        sa.Column("display_secondary_temp", sa.String(), nullable=True),
        sa.Column("display_tertiary_temp", sa.String(), nullable=True),
        sa.Column("display_age_temp", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["origin_recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.create_index(op.f("ix_recipes_name"), "recipes", ["name"], unique=False)
    op.create_index(
        "ix_recipes_name_version", "recipes", ["name", "version"], unique=False
    )
    op.create_index(
        "ix_recipes_origin_recipe_id", "recipes", ["origin_recipe_id"], unique=False
    )
    op.create_table(
        "references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("favicon_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_references_id"), "references", ["id"], unique=False)
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_number", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("brewer", sa.String(), nullable=False),
        sa.Column("brew_date", sa.DateTime(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_batches_id"), "batches", ["id"], unique=False)
    op.create_index("ix_batches_recipe_id", "batches", ["recipe_id"], unique=False)
    op.create_index(
        "ix_batches_recipe_id_batch_number",
        "batches",
        ["recipe_id", "batch_number"],
        unique=False,
    )
    op.create_table(
        "choices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("choice_text", sa.String(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_choices_choice_text"), "choices", ["choice_text"], unique=False
    )
    op.create_index(op.f("ix_choices_id"), "choices", ["id"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("boil_size", sa.Integer(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("tun_volume", sa.Integer(), nullable=True),
        sa.Column("tun_weight", sa.Integer(), nullable=True),
        sa.Column("tun_specific_heat", sa.Integer(), nullable=True),
        sa.Column("top_up_water", sa.Integer(), nullable=True),
        sa.Column("trub_chiller_loss", sa.Integer(), nullable=True),
        sa.Column("evap_rate", sa.Integer(), nullable=True),
        sa.Column("boil_time", sa.Integer(), nullable=True),
        sa.Column("calc_boil_volume", sa.Boolean(), nullable=True),
        sa.Column("lauter_deadspace", sa.Integer(), nullable=True),
        sa.Column("top_up_kettle", sa.Integer(), nullable=True),
        sa.Column("hop_utilization", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("display_boil_size", sa.String(length=255), nullable=True),
        sa.Column("display_batch_size", sa.String(length=255), nullable=True),
        sa.Column("display_tun_volume", sa.String(length=255), nullable=True),
        sa.Column("display_tun_weight", sa.String(length=255), nullable=True),
        sa.Column("display_top_up_water", sa.String(length=255), nullable=True),
        sa.Column("display_trub_chiller_loss", sa.String(length=255), nullable=True),
        sa.Column("display_lauter_deadspace", sa.String(length=255), nullable=True),
        sa.Column("display_top_up_kettle", sa.String(length=255), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_equipment_name"),
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(
        op.f("ix_equipment_recipe_id"), "equipment", ["recipe_id"], unique=False
    )
    op.create_table(
        "mash_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("infuse_amount", sa.Integer(), nullable=True),
        sa.Column("step_time", sa.Integer(), nullable=True),
        sa.Column("step_temp", sa.Integer(), nullable=True),
        sa.Column("ramp_time", sa.Integer(), nullable=True),
        sa.Column("end_temp", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("water_grain_ratio", sa.String(length=255), nullable=True),
        sa.Column("decoction_amt", sa.String(length=255), nullable=True),
        sa.Column("infuse_temp", sa.Integer(), nullable=True),
        sa.Column("display_step_temp", sa.String(length=255), nullable=True),
        sa.Column("display_infuse_amt", sa.String(length=255), nullable=True),
        sa.Column("mash_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mash_id"],
            ["mash.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mash_step_id"), "mash_step", ["id"], unique=False)
    op.create_table(
        "recipe_fermentables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("yield_", sa.Float(), nullable=True),
        sa.Column("color", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("supplier", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("potential", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("cost_per_unit", sa.Float(), nullable=True),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("lot_number", sa.String(), nullable=True),
        sa.Column("exclude_from_total", sa.Boolean(), nullable=True),
        sa.Column("not_fermentable", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("substitutes", sa.String(), nullable=True),
        sa.Column("used_in", sa.String(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_fermentables_id"), "recipe_fermentables", ["id"], unique=False
    )
    op.create_table(
        "recipe_hops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("hsi", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("use", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("display_amount", sa.String(), nullable=True),
        sa.Column("inventory", sa.String(), nullable=True),
        sa.Column("display_time", sa.String(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_hops_id"), "recipe_hops", ["id"], unique=False)
    op.create_table(
        "recipe_miscs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("use", sa.String(), nullable=True),
        sa.Column("amount_is_weight", sa.Boolean(), nullable=True),
        sa.Column("use_for", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("display_amount", sa.String(), nullable=True),
        sa.Column("inventory", sa.Integer(), nullable=True),
        sa.Column("display_time", sa.String(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_miscs_id"), "recipe_miscs", ["id"], unique=False)
    op.create_table(
        "recipe_yeasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("amount_is_weight", sa.Boolean(), nullable=True),
        sa.Column("laboratory", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("min_temperature", sa.Float(), nullable=True),
        sa.Column("max_temperature", sa.Float(), nullable=True),
        sa.Column("flocculation", sa.String(), nullable=True),
        sa.Column("attenuation", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("best_for", sa.String(), nullable=True),
        sa.Column("times_cultured", sa.Integer(), nullable=True),
        sa.Column("max_reuse", sa.Integer(), nullable=True),
        sa.Column("add_to_secondary", sa.Boolean(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_yeasts_id"), "recipe_yeasts", ["id"], unique=False)
    op.create_table(
        "style_guidelines",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("block_heading", sa.String(length=255), nullable=True),
        sa.Column("circle_image", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=255), nullable=True),
        sa.Column("clarity", sa.String(length=255), nullable=True),
        sa.Column("perceived_malt_and_aroma", sa.Text(), nullable=True),
        sa.Column("perceived_hop_and_aroma", sa.Text(), nullable=True),
        sa.Column("perceived_bitterness", sa.Text(), nullable=True),
        sa.Column("fermentation_characteristics", sa.Text(), nullable=True),
        sa.Column("body", sa.String(length=255), nullable=True),
        sa.Column("additional_notes", sa.Text(), nullable=True),
        sa.Column("og", sa.String(length=255), nullable=True),
        sa.Column("fg", sa.String(length=255), nullable=True),
        sa.Column("abv", sa.String(length=255), nullable=True),
        sa.Column("ibu", sa.String(length=255), nullable=True),
        sa.Column("ebc", sa.String(length=255), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_style_guidelines_recipe_id"),
        "style_guidelines",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "styles",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("category_number", sa.Integer(), nullable=True),
        sa.Column("style_letter", sa.String(length=255), nullable=True),
        sa.Column("style_guide", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("og_min", sa.String(length=255), nullable=True),
        sa.Column("og_max", sa.String(length=255), nullable=True),
        sa.Column("fg_min", sa.String(length=255), nullable=True),
        sa.Column("fg_max", sa.String(length=255), nullable=True),
        sa.Column("ibu_min", sa.String(length=255), nullable=True),
        sa.Column("ibu_max", sa.String(length=255), nullable=True),
        sa.Column("color_min", sa.String(length=255), nullable=True),
        sa.Column("color_max", sa.String(length=255), nullable=True),
        sa.Column("carb_min", sa.String(length=255), nullable=True),
        sa.Column("carb_max", sa.String(length=255), nullable=True),
        sa.Column("abv_max", sa.String(length=255), nullable=True),
        sa.Column("abv_min", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("profile", sa.Text(), nullable=True),
        sa.Column("ingredients", sa.Text(), nullable=True),
        sa.Column("examples", sa.Text(), nullable=True),
        sa.Column("display_og_min", sa.String(length=255), nullable=True),
        sa.Column("display_og_max", sa.String(length=255), nullable=True),
        sa.Column("display_fg_min", sa.String(length=255), nullable=True),
        sa.Column("display_fg_max", sa.String(length=255), nullable=True),
        sa.Column("display_color_min", sa.String(length=255), nullable=True),
        sa.Column("display_color_max", sa.String(length=255), nullable=True),
        sa.Column("og_range", sa.String(length=255), nullable=True),
        sa.Column("fg_range", sa.String(length=255), nullable=True),
        sa.Column("ibu_range", sa.String(length=255), nullable=True),
        sa.Column("carb_range", sa.String(length=255), nullable=True),
        sa.Column("color_range", sa.String(length=255), nullable=True),
        sa.Column("abv_range", sa.String(length=255), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_styles_recipe_id"), "styles", ["recipe_id"], unique=False)
    op.create_table(
        "water",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("calcium", sa.Integer(), nullable=True),
        sa.Column("bicarbonate", sa.Integer(), nullable=True),
        sa.Column("sulfate", sa.Integer(), nullable=True),
        sa.Column("chloride", sa.Integer(), nullable=True),
        sa.Column("sodium", sa.Integer(), nullable=True),
        sa.Column("magnesium", sa.Integer(), nullable=True),
        sa.Column("ph", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("display_amount", sa.String(length=255), nullable=True),
        sa.Column("inventory", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_water_id"), "water", ["id"], unique=False)
    op.create_table(
        "batch_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id"),
    )
    op.create_index("ix_batch_logs_batch_id", "batch_logs", ["batch_id"], unique=False)
    op.create_index(op.f("ix_batch_logs_id"), "batch_logs", ["id"], unique=False)
    op.create_table(
        "inventory_fermentables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("yield_", sa.Float(), nullable=True),
        sa.Column("color", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("supplier", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("potential", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("cost_per_unit", sa.Float(), nullable=True),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("lot_number", sa.String(), nullable=True),
        sa.Column("exclude_from_total", sa.Boolean(), nullable=True),
        sa.Column("not_fermentable", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("substitutes", sa.String(), nullable=True),
        sa.Column("used_in", sa.String(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("use", sa.String(), nullable=True),
        sa.Column("amount_is_weight", sa.Boolean(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("min_temperature", sa.Float(), nullable=True),
        sa.Column("max_temperature", sa.Float(), nullable=True),
        sa.Column("flocculation", sa.String(), nullable=True),
        sa.Column("attenuation", sa.Float(), nullable=True),
        sa.Column("max_reuse", sa.Integer(), nullable=True),
        sa.Column("inventory", sa.Float(), nullable=True),
        sa.Column("display_amount", sa.String(), nullable=True),
        sa.Column("display_time", sa.String(), nullable=True),
        sa.Column("batch_size", sa.Float(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_fermentables_id"),
        "inventory_fermentables",
        ["id"],
        unique=False,
    )
    op.create_table(
        "inventory_hops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("hsi", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("use", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("display_amount", sa.String(), nullable=True),
        sa.Column("inventory", sa.String(), nullable=True),
        sa.Column("display_time", sa.String(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_hops_id"), "inventory_hops", ["id"], unique=False
    )
    op.create_table(
        "inventory_miscs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("use", sa.String(), nullable=True),
        sa.Column("amount_is_weight", sa.Boolean(), nullable=True),
        sa.Column("use_for", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("display_amount", sa.String(), nullable=True),
        sa.Column("inventory", sa.Integer(), nullable=True),
        sa.Column("display_time", sa.String(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_miscs_id"), "inventory_miscs", ["id"], unique=False
    )
    op.create_table(
        "inventory_yeasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("form", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("amount_is_weight", sa.Boolean(), nullable=True),
        sa.Column("laboratory", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("min_temperature", sa.Float(), nullable=True),
        sa.Column("max_temperature", sa.Float(), nullable=True),
        sa.Column("flocculation", sa.String(), nullable=True),
        sa.Column("attenuation", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("best_for", sa.String(), nullable=True),
        sa.Column("times_cultured", sa.Integer(), nullable=True),
        sa.Column("max_reuse", sa.Integer(), nullable=True),
        sa.Column("add_to_secondary", sa.Boolean(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_yeasts_id"), "inventory_yeasts", ["id"], unique=False
    )
    op.create_table(
        "recipe_adjunct",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_adjunct_id"), "recipe_adjunct", ["id"], unique=False
    )
    op.create_table(
        "recipe_dry_extract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_dry_extract_id"), "recipe_dry_extract", ["id"], unique=False
    )
    op.create_table(
        "recipe_grain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diastatic_power", sa.Float(), nullable=True),
        sa.Column("moisture", sa.Float(), nullable=True),
        sa.Column("protein", sa.Float(), nullable=True),
        sa.Column("coarse_fine_diff", sa.Float(), nullable=True),
        sa.Column("extract", sa.Float(), nullable=True),
        sa.Column("acidity", sa.Float(), nullable=True),
        sa.Column("friability", sa.Float(), nullable=True),
        sa.Column("free_amino_nitrogen", sa.Float(), nullable=True),
        sa.Column("max_in_batch", sa.Float(), nullable=True),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_grain_id"), "recipe_grain", ["id"], unique=False)
    op.create_table(
        "recipe_liquid_extract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_liquid_extract_id"),
        "recipe_liquid_extract",
        ["id"],
        unique=False,
    )
    op.create_table(
        "recipe_other",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_other_id"), "recipe_other", ["id"], unique=False)
    op.create_table(
        "recipe_sugar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["recipe_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_sugar_id"), "recipe_sugar", ["id"], unique=False)
    op.create_table(
        "inventory_adjunct",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_adjunct_id"), "inventory_adjunct", ["id"], unique=False
    )
    op.create_table(
        "inventory_dry_extract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_dry_extract_id"),
        "inventory_dry_extract",
        ["id"],
        unique=False,
    )
    op.create_table(
        "inventory_grain",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diastatic_power", sa.Float(), nullable=True),
        sa.Column("moisture", sa.Float(), nullable=True),
        sa.Column("protein", sa.Float(), nullable=True),
        sa.Column("coarse_fine_diff", sa.Float(), nullable=True),
        sa.Column("extract", sa.Float(), nullable=True),
        sa.Column("acidity", sa.Float(), nullable=True),
        sa.Column("friability", sa.Float(), nullable=True),
        sa.Column("free_amino_nitrogen", sa.Float(), nullable=True),
        sa.Column("max_in_batch", sa.Float(), nullable=True),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_grain_id"), "inventory_grain", ["id"], unique=False
    )
    op.create_table(
        "inventory_liquid_extract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_liquid_extract_id"),
        "inventory_liquid_extract",
        ["id"],
        unique=False,
    )
    op.create_table(
        "inventory_other",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_other_id"), "inventory_other", ["id"], unique=False
    )
    op.create_table(
        "inventory_sugar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fermentable_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fermentable_id"],
            ["inventory_fermentables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_sugar_id"), "inventory_sugar", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_sugar_id"), table_name="inventory_sugar")
    op.drop_table("inventory_sugar")
    op.drop_index(op.f("ix_inventory_other_id"), table_name="inventory_other")
    op.drop_table("inventory_other")
    op.drop_index(
        op.f("ix_inventory_liquid_extract_id"), table_name="inventory_liquid_extract"
    )
    op.drop_table("inventory_liquid_extract")
    op.drop_index(op.f("ix_inventory_grain_id"), table_name="inventory_grain")
    op.drop_table("inventory_grain")
    op.drop_index(
        op.f("ix_inventory_dry_extract_id"), table_name="inventory_dry_extract"
    )
    op.drop_table("inventory_dry_extract")
    op.drop_index(op.f("ix_inventory_adjunct_id"), table_name="inventory_adjunct")
    op.drop_table("inventory_adjunct")
    op.drop_index(op.f("ix_recipe_sugar_id"), table_name="recipe_sugar")
    op.drop_table("recipe_sugar")
    op.drop_index(op.f("ix_recipe_other_id"), table_name="recipe_other")
    op.drop_table("recipe_other")
    op.drop_index(
        op.f("ix_recipe_liquid_extract_id"), table_name="recipe_liquid_extract"
    )
    op.drop_table("recipe_liquid_extract")
    op.drop_index(op.f("ix_recipe_grain_id"), table_name="recipe_grain")
    op.drop_table("recipe_grain")
    op.drop_index(op.f("ix_recipe_dry_extract_id"), table_name="recipe_dry_extract")
    op.drop_table("recipe_dry_extract")
    op.drop_index(op.f("ix_recipe_adjunct_id"), table_name="recipe_adjunct")
    op.drop_table("recipe_adjunct")
    op.drop_index(op.f("ix_inventory_yeasts_id"), table_name="inventory_yeasts")
    op.drop_table("inventory_yeasts")
    op.drop_index(op.f("ix_inventory_miscs_id"), table_name="inventory_miscs")
    op.drop_table("inventory_miscs")
    op.drop_index(op.f("ix_inventory_hops_id"), table_name="inventory_hops")
    op.drop_table("inventory_hops")
    op.drop_index(
        op.f("ix_inventory_fermentables_id"), table_name="inventory_fermentables"
    )
    op.drop_table("inventory_fermentables")
    op.drop_index(op.f("ix_batch_logs_id"), table_name="batch_logs")
    op.drop_index("ix_batch_logs_batch_id", table_name="batch_logs")
    op.drop_table("batch_logs")
    op.drop_index(op.f("ix_water_id"), table_name="water")
    op.drop_table("water")
    op.drop_index(op.f("ix_styles_recipe_id"), table_name="styles")
    op.drop_table("styles")
    op.drop_index(op.f("ix_style_guidelines_recipe_id"), table_name="style_guidelines")
    op.drop_table("style_guidelines")
    op.drop_index(op.f("ix_recipe_yeasts_id"), table_name="recipe_yeasts")
    op.drop_table("recipe_yeasts")
    op.drop_index(op.f("ix_recipe_miscs_id"), table_name="recipe_miscs")
    op.drop_table("recipe_miscs")
    op.drop_index(op.f("ix_recipe_hops_id"), table_name="recipe_hops")
    op.drop_table("recipe_hops")
    op.drop_index(op.f("ix_recipe_fermentables_id"), table_name="recipe_fermentables")
    op.drop_table("recipe_fermentables")
    op.drop_index(op.f("ix_mash_step_id"), table_name="mash_step")
    op.drop_table("mash_step")
    op.drop_index(op.f("ix_equipment_recipe_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_choices_id"), table_name="choices")
    op.drop_index(op.f("ix_choices_choice_text"), table_name="choices")
    op.drop_table("choices")
    op.drop_index("ix_batches_recipe_id_batch_number", table_name="batches")
    op.drop_index("ix_batches_recipe_id", table_name="batches")
    op.drop_index(op.f("ix_batches_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_references_id"), table_name="references")
    op.drop_table("references")
    op.drop_index("ix_recipes_origin_recipe_id", table_name="recipes")
    op.drop_index("ix_recipes_name_version", table_name="recipes")
    op.drop_index(op.f("ix_recipes_name"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_questions_question_text"), table_name="questions")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_mash_id"), table_name="mash")
    op.drop_table("mash")
    # ### end Alembic commands ###
