from pydantic import BaseModel, ConfigDict


class User(BaseModel):
    """
    Description:

    This class represents the user table in the database.

    Use cases:

    - Validate data before entering it into the database.

    Notes:

    - the id field is optional because it is generated by the database.

    """

    username: str
    password: str

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "username": "brewmaster",
                "password": "S3curePassw0rd!",
            }
        }
    )
