from pydantic import BaseModel
from typing import Optional

WATER_PROFILE_EXAMPLE = {
    "name": "Burton-on-Trent IPA",
    "version": 1,
    "amount": 25,
    "calcium": 275,
    "bicarbonate": 260,
    "sulfate": 650,
    "chloride": 35,
    "sodium": 25,
    "magnesium": 45,
    "ph": 8,
    "notes": "Idealized profile for hoppy ales with high sulfate to chloride ratio.",
    "display_amount": "25 L",
    "inventory": 1,
}


class WaterProfileBase(BaseModel):
    """
    Description:

    This class represents the water_profile table in the database.

    Use cases:

    - Validate data before entering it into the database.

    Notes:

    - the id field is optional because it is generated by the database.

    """

    name: Optional[str] = None
    version: Optional[int] = None
    amount: Optional[int] = None
    calcium: Optional[int] = None
    bicarbonate: Optional[int] = None
    sulfate: Optional[int] = None
    chloride: Optional[int] = None
    sodium: Optional[int] = None
    magnesium: Optional[int] = None
    ph: Optional[int] = None
    notes: Optional[str] = None
    display_amount: Optional[str] = None
    inventory: Optional[int] = None

    class Config:
        schema_extra = {"example": WATER_PROFILE_EXAMPLE}
