from pydantic import BaseModel
from typing import Optional


class WaterProfileBase(BaseModel):
    """
    Description:

    This class represents the water_profile table in the database.

    Use cases:

    - Validate data before entering it into the database.

    Notes:

    - the id field is optional because it is generated by the database.

    """

    name: Optional[str] = None
    version: Optional[int] = None
    amount: Optional[int] = None
    calcium: Optional[int] = None
    bicarbonate: Optional[int] = None
    sulfate: Optional[int] = None
    chloride: Optional[int] = None
    sodium: Optional[int] = None
    magnesium: Optional[int] = None
    ph: Optional[int] = None
    notes: Optional[str] = None
    display_amount: Optional[str] = None
    inventory: Optional[int] = None
